# Generated by Django 3.0.2 on 2020-03-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewanswer',
            options={'verbose_name': 'Ответ на отзыв', 'verbose_name_plural': 'Ответы на отзывы'},
        ),
        migrations.AlterField(
            model_name='callingmailing',
            name='phoneNumber',
            field=models.CharField(max_length=25, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Номер телефона'),
        ),
    ]
