# Generated by Django 3.0.2 on 2020-03-20 12:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpSystem', '0002_auto_20200320_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
    ]
