# Generated by Django 3.0.2 on 2020-03-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpSystem', '0004_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.IntegerField(null=True, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(null=True, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='emailmailing',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
