# Generated by Django 3.0.2 on 2020-03-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpSystem', '0005_auto_20200324_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingmailing',
            name='phoneNumber',
            field=models.CharField(max_length=25, unique=True, verbose_name='Номер телефона'),
        ),
    ]
