# Generated by Django 3.0.2 on 2020-03-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpSystem', '0009_article_likescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shortDescription',
            field=models.TextField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
    ]
