# Generated by Django 3.0.2 on 2020-03-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpSystem', '0010_article_shortdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='shortDescription',
            field=models.TextField(max_length=455, null=True, verbose_name='Краткое описание'),
        ),
    ]
