# Generated by Django 3.0.2 on 2020-03-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpSystem', '0011_auto_20200324_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmailing',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата отправки'),
        ),
    ]
