# Generated by Django 3.0.2 on 2020-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpSystem', '0012_auto_20200324_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingmailing',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата отправки'),
        ),
    ]
